[options]
    statusline_inactive_separator = "nil"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
  name = "fzf"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "nil"
  auto-completion-tab-key-behavior = "smart"
  auto-completion-complete-with-key-sequence = "nil"
  auto_completion_delay = 150

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 25

[[layers]]
  name = "tmux"

[[layers]]
  name = "git"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#csharp"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"
